FROM ubuntu:18.04

RUN apt-get update && \
  apt-get -y upgrade && \
  apt-get -y install --no-install-recommends \
    build-essential \
    git \
    lsb-release \
    ruby \
    ruby-dev \
    rubygems && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
RUN gem install --no-document fpm

VOLUME /code
WORKDIR /code

ENTRYPOINT make package
