name: NINJA CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: cd NINJA && make
    - name: make check
      run: cd NINJA && make check
