name: NINJA CI

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-18.04
    container:
      image: traviswheelerlab/ninja-build:1.0.1
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make check

  check-format:
    runs-on: ubuntu-18.04
    container:
      image: traviswheelerlab/ninja-build:1.0.1
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make check-format

  build:
    runs-on: ubuntu-18.04
    needs: check
    container:
      image: traviswheelerlab/ninja-build:1.0.1
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make
      - name: persist build archive
        uses: actions/upload-artifact@v1
        with:
          name: build-archive
          path: .
