name: NINJA CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: traviswheelerlab/ninja-build:1.0.1
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make

  release:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: NINJA version ${{ github.ref }}
      - name: create version file
        run: echo '${{ github.ref }}' > VERSION
      
      # Binary package (zip)

      - name: create binary package
        run: zip ninja-binary-linux.zip Ninja README.md LICENSE VERSION
      - name: attach binary package
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ninja-binary-linux.zip
          asset_name: ninja-binary-linux.zip
          asset_content_type: application/zip