name: NINJA CI

on: [pull_request, push]

jobs:
  check:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: make check
      run: make check
